### PR TITLE
Fix Micronaut URL

### PR DESCRIPTION
**Pull request by alexlostorto**
Meow 🐱

### CODE REVIEW

**Comment by wmartinmimi** [comment]
No, launch.micronaut.io is the correct url lol.

**Comment by alexlostorto** [comment]
It doesn't work though!

If you click it, it goes to: https://github.com/wmartinmimi/mn-create/blob/main/launch.micronaut.io

**Comment by wmartinmimi** [comment]
oh huh

**Comment by wmartinmimi** [comment]
should be fixed now

**Pull request closed without merging**
